apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/bitnami.yaml
  - sources/grafana.yaml
  - sources/jetstack.yaml
  - sources/opentelemetry.yaml
  - sources/prometheus.yaml
  - controllers/cert-manager.yaml
  - controllers/opentelemetry-operator.yaml
  - controllers/kube-prometheus-stack.yaml
  - controllers/loki.yaml
